---
- name: Gather all Tags for vCenter
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Login task
      include_tasks: login.yml

    - name: Get Tags from vCenter
      uri:
        url: https://{{ vcenter_server }}/rest/com/vmware/cis/tagging/tag
        force_basic_auth: yes
        validate_certs: "{{ validate_certs }}"
        headers:
          Cookie: "{{ login.set_cookie }}"
      register: vTags

    - name: Print names of Tags in the given vCenter
      debug:
        msg: "{{ item }}"
      with_items: "{{ vTags.json.value }}"
