---
- name: Gather all VMs for vCenter
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Login task
      include_tasks: login.yml

    - name: Get VMs from vCenter
      uri:
        url: https://{{ vcenter_server }}/rest/vcenter/vm
        force_basic_auth: yes
        validate_certs: "{{ validate_certs }}"
        headers:
          Cookie: "{{ login.set_cookie }}"
      register: vVMs

    - name: Print names of VMs in the given vCenter
      debug:
        msg: "{{ item.name }}"
      with_items: "{{ vVMs.json.value }}"
