---
- name: Gather all networks for vCenter
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Login task
      include_tasks: login.yml

    - name: Get networks from vCenter
      uri:
        url: https://{{ vcenter_server }}/rest/vcenter/network
        force_basic_auth: yes
        validate_certs: "{{ validate_certs }}"
        headers:
          Cookie: "{{ login.set_cookie }}"
      register: vnetworks

    - name: Print names of networks in the given vCenter
      debug:
        msg: "{{ item.name }}"
      with_items: "{{ vnetworks.json.value }}"
