---
- name: Gather all clusters for vCenter
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Login task
      include_tasks: login.yml

    - name: Get clusters from vCenter
      uri:
        url: https://{{ vcenter_server }}/rest/vcenter/cluster
        force_basic_auth: yes
        validate_certs: "{{ validate_certs }}"
        headers:
          Cookie: "{{ login.set_cookie }}"
      register: vClusters

    - name: Print names of clusters in the given vCenter
      debug:
        msg: "{{ item.name }}"
      with_items: "{{ vClusters.json.value }}"
