---
- name: Gather all Categories for vCenter
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Login task
      include_tasks: login.yml

    - name: Get Categories from vCenter
      uri:
        url: https://{{ vcenter_server }}/rest/com/vmware/cis/tagging/category
        force_basic_auth: yes
        validate_certs: "{{ validate_certs }}"
        headers:
          Cookie: "{{ login.set_cookie }}"
      register: vCategories

    - name: Print names of Categories in the given vCenter
      debug:
        msg: "{{ item }}"
      with_items: "{{ vCategories.json.value }}"
